### PR TITLE
logging: Add sandbox CLI option

### LINKED ISSUE #87: cmdline: accept a 'sandbox' argument to aid with log annotation
# Description of problem

The proxy does not know (afaict) which sandbox/container it is routing, and thus cannot annotate any logs it generates.

# Expected result

It might aid debugging if we can add the annotation. For instance, on an agent yamux fail, I got:
```
time="2018-07-02T11:49:16.217469645+01:00" level=info msg="2018/07/02 10:49:16 [ERR] yamux: keepalive failed: i/o deadline reached\n" name=kata-proxy pid=25683 source=agent
```

routed out by https://github.com/kata-containers/proxy/blob/master/proxy.go#L187, but it does not indicate which sandbox/container it relates to, and that information is currently not to hand in the proxy.

I think the only way to do this is to pass the sandbox ID in over at https://github.com/kata-containers/runtime/blob/master/virtcontainers/kata_proxy.go#L41 on the proxy invocation command line.

### PR DESCRIPTION
**Pull request by jodh-intel**
Added a new `-sandbox` command-line option. This is not required by the
proxy itself, but is used to add a `sandbox` log field to make log
analysis easier.

Also changed the initial log message to show the standard "announce" message tag along with fields for each of the command-line options.

Fixes #87.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
Note: the `-sandbox` option is not mandatory (yet). The plan is:

- land this PR.
- update the runtime/vc to launch the proxy with the new `-sandbox` option.
- raise a new proxy PR to make the option mandatory.

Alternatively, I could raise a runtime PR to pass the option now and we could land them together.

I don't mind either way - thoughts @sboeuf, @bergwolf, @grahamwhaley?

**Comment by grahamwhaley** [comment]
I thought we might add it as an optinal (that is, not mandatory) in order to not break backwards compatibility. We could then make it mandatory later once all versions support it and have filtered through and/or been deprecated.

**Comment by gnawux** [comment]
As it is used in logs only, I think optional is enough.

**Comment by jodh-intel** [comment]
Thanks guys. The option is currently optional so this should work for us ;) I'll raise a runtime PR to add the option when starting the kata proxy and block on this PR landing...

File: proxy.go [hunk 1]
```diff
@@ -119,13 +124,14 @@ func unixAddr(uri string) (string, error) {
 
 func logger() *logrus.Entry {
 	return proxyLog.WithFields(logrus.Fields{
-		"name":   proxyName,
-		"pid":    os.Getpid(),
-		"source": "proxy",
+		"name":    proxyName,
+		"pid":     os.Getpid(),
+		"source":  "proxy",
+		"sandbox": sandboxID,
```
Comment (devimc) [inline proxy.go]: since `sandboxID` is optional, I think you should add it only if it's not empty, right?

Comment (jodh-intel) [reply proxy.go]: I guess that's fair :) Branch updated.

**Comment by jodh-intel** [comment]
Hi @raravena80 - amusing problem - Travis is failing over here, but only for osx:

```
$ .ci/static-checks.sh
/Users/travis/gopath/src/github.com/kata-containers/tests/.ci/static-checks.sh: line 24: typeset: -A: invalid option
typeset: usage: typeset [-afFirtx] [-p] name[=value] ...
```

The `static-checks.sh` script is now failing as I recently updated it on https://github.com/kata-containers/tests/pull/471. The problem here appears to be due to osx not providing a new enough version of bash that supports associative arrays. Any idea how to fix this?

**Comment by devimc** [comment]
lgtm

**Comment by jodh-intel** [comment]
@raravena80 - I think I've fixed it by installing bash using homebrew.

**Comment by jodh-intel** [comment]
Tests added! ;)

**Comment by raravena80** [comment]
@jodh-intel good to hear. It would be interesting to find out what version of bash travis is using. This is what's on my laptop for High Sierra:

```
$ bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17)
Copyright (C) 2007 Free Software Foundation, Inc.
```

**Comment by jodh-intel** [comment]
@raravena80 - I don't think the version was logged but bash 4 added associative arrays (`typeset -A`) so it is likely to be version 3.*.
