### PR TITLE
proxy: Maintain communication state with a heartbeat

### LINKED ISSUE #70: yamux: keepalive failed: i/o deadline reached
see https://github.com/kata-containers/agent/issues/231

### PR DESCRIPTION
**Pull request by sboeuf**
We are trying to disable the feature keepalive introduced by Yamux
both on the client (kata-proxy) and server (kata-agent) sides. The
reason being we don't want to get Yamux errors in case we pause the
VM. The proxy side has already been disabled and we are about to
disable it on the agent side too. Problem is, we sometimes run into
a weird issue where the communication between the proxy and the agent
hangs.

It's related to the emulated serial port created by Qemu which is not
getting out of its sleeping loop for some cases. This issue is still
under investigation, but a simple fix is to actually write more data
to the serial port to wake it up. This workaround is needed since
disabling Yamux keepalive solves several issues, particularly one
related to our long running soak tests.

That's why this commit enables a simple "keepalive" feature, except
it does not check for any error. The idea being to simply sending
something out through this serial port.

Fixes #70

Signed-off-by: Sebastien Boeuf <sebastien.boeuf@intel.com>

### CODE REVIEW

**Comment by sboeuf** [comment]
Relates to https://github.com/kata-containers/agent/pull/263

**Comment by bergwolf** [comment]
> The reason being we don't want to get Yamux errors in case we pause the VM.

If that is the root cause, would this commit help? https://github.com/hashicorp/yamux/commit/4c2fe0dc4154fb12f69cdb72a1b061de446b4d71

We already have it at the runtime side but I don't think we have it in proxy or agent.

**Comment by sboeuf** [comment]
@bergwolf I doubt the patch will change anything to the case explained by @devimc here: https://github.com/kata-containers/agent/issues/231#issue-319584238
The thing is, I am not sure pausing the container will end up into an `ErrSessionShutdown`, hence the patch you're pointing will have no effect.

**Comment by devimc** [comment]
CI is not happy

```
proxy.go:1::warning: file is not gofmted with -s (gofmt)
```

**Comment by sboeuf** [comment]
recheck

File: proxy.go [hunk 1]
```diff
@@ -47,15 +47,39 @@ var sandboxID string
...
+
+	for {
+		if session.IsClosed() {
+			break
+		}
+
+		session.Ping()
+
+		// 1 Hz heartbeat
+		time.Sleep(time.Second)
```
Comment (grahamwhaley) [inline proxy.go]: Just noting, I suspect 1s might be a good balance between too much traffic and keeping the link alive (waking out of freeze). For reference, I believe the default keepAlive timing we are effectively replacing was 30s.

File: proxy.go [hunk 2]
```diff
@@ -47,15 +47,39 @@ var sandboxID string
...
+	}
+}
+
 func serve(servConn io.ReadWriteCloser, proto, addr string, results chan error) (net.Listener, error) {
 	sessionConfig := yamux.DefaultConfig()
 	// Disable keepAlive since we don't know how much time a container can be paused
 	sessionConfig.EnableKeepAlive = false
+	sessionConfig.ConnectionWriteTimeout = time.Second
```
Comment (grahamwhaley) [inline proxy.go]: Any particular reason you set this - the default is 10s in the Yamux configs I think.

**Comment by grahamwhaley** [comment]
A note for @chavafg @cboylan - I see we have a Zuul fail on the CI list here - but if I click the 'details' link it takes me off to what looks like the Zuul frontpage (https://zuul.openstack.org/). Will we eventually have the hot links take us off to a nice gui summary for the failed build? Just wondering :-)

File: proxy.go (hunk 2 above)
Comment (sboeuf) [reply proxy.go]: By default, the ping command will wait for 10s to realize a write failed, and I thought it would be better to reduce this to 1s as we're not killing the communication if such error now happens. If we keep this to 10s by default, we might end up with cases where no heartbeat will be sent during 11s.

**Comment by sboeuf** [comment]
@devimc well, using a long timeout is not appropriate because we'll hit the same issue and it'll be longer to unblock the hanging communication. This does not sounds like a viable option IMO.

**Comment by grahamwhaley** [comment]
I happened to do that yesterday whilst testing for the hangout. As well as bumping the timeout on the keepalive, maybe we want to bump the connectionwritetimeout as well/instead - as iirc it was actually the connection write timeout on the keepalive ping that was failing, not the ping itself per-se ?

**Comment by sboeuf** [comment]
@grahamwhaley bumping the write timeout will only postpone the moment where the failure will happen (in case the VM is paused).

**Comment by grahamwhaley** [comment]
Ah, yes - true! I had my 'very slow runtime' failure case in mind.

**Comment by devimc** [comment]
@sboeuf enabling keepAlive in both sides, works for me

*kata-proxy*
```patch
diff --git a/proxy.go b/proxy.go
index 802d80e..705c18d 100644
--- a/proxy.go
+++ b/proxy.go
@@ -50,7 +50,9 @@ var proxyLog = logrus.New()
 func serve(servConn io.ReadWriteCloser, proto, addr string, results chan error) (net.Listener, error) {
        sessionConfig := yamux.DefaultConfig()
        // Disable keepAlive since we don't know how much time a container can be paused
-       sessionConfig.EnableKeepAlive = false
+       sessionConfig.KeepAliveInterval = 10 * time.Second
+       sessionConfig.ConnectionWriteTimeout = time.Hour * 24 * 365
+
        session, err := yamux.Client(servConn, sessionConfig)
        if err != nil {
                return nil, err
```


*kata-agent*
```patch
diff --git a/channel.go b/channel.go
index 624c81a..bd6b115 100644
--- a/channel.go
+++ b/channel.go
@@ -13,6 +13,7 @@ import (
        "os"
        "path/filepath"
        "strings"
+       "time"
 
        "github.com/hashicorp/yamux"
        "github.com/mdlayher/vsock"
@@ -164,6 +165,8 @@ func (c *serialChannel) listen() (net.Listener, error) {
        config := yamux.DefaultConfig()
 
        config.LogOutput = yamuxWriter{}
+       config.KeepAliveInterval = 10 * time.Second
+       config.ConnectionWriteTimeout = time.Hour * 24 * 365
 
        // Initialize Yamux server.
        session, err := yamux.Server(c.serialConn, config)
```

File: proxy.go [hunk 3]
```diff
@@ -47,15 +47,39 @@ var sandboxID string
 
 var proxyLog = logrus.New()
 
+// This function is meant to run in a go routine since it will send ping
+// commands every second. It behaves as a heartbeat to maintain a proper
+// communication state with the Yamux server in the agent.
+func heartBeat(session *yamux.Session) {
```
Comment (devimc) [inline proxy.go]: yamux `config.KeepAliveInterval` already do this,  we just need to increase `config.ConnectionWriteTimeout`

**Comment by sboeuf** [comment]
@devimc of course it works, you have a heartbeat beating every 10s with a write timeout of 1 year. So basically, you're not running into the hang issue because something is written every 10s, which maintain the connection alive, and at the same time, if this heartbeat hangs because the VM has been paused, it will not generate an error before it reaches one year.
But I feel that using one year here is sort of weird, and I don't think we should use the keepalive at all.
@bergwolf @grahamwhaley WDYT ? That'd be great if we could take a decision on this so that we unblock the metrics.

File: proxy.go (hunk 1 above)
Comment (devimc) [reply proxy.go]: my biggest concern here is how much overhead add this?

Comment (sboeuf) [reply proxy.go]: What do you mean by overhead ? Amount of data we're sending to the agent ?

Comment (sboeuf) [reply proxy.go]: I get the cpu usage, but could you elaborate a bit more on memory consumption and bottle necks ?

Comment (devimc) [reply proxy.go]: I ran some tests and lgtm

**Comment by devimc** [comment]
lgtm

**Comment by cboylan** [comment]
> A note for @chavafg @cboylan - I see we have a Zuul fail on the CI list here - but if I click the 'details'
> link it takes me off to what looks like the Zuul frontpage (https://zuul.openstack.org/). Will we eventually
> have the hot links take us off to a nice gui summary for the failed build? Just wondering :-)

@grahamwhaley this is a current known deficiency and part of the reason we are leaving distinct comments with logs. The current details page will get you to the live status page which is great when jobs are running but less so once they complete and report.

The plan to correct this is to support GitHub's new status check api, https://help.github.com/articles/about-status-checks/, and report details in that way. This work hasn't started yet. If anyone is interested in helping I'd be happy to help get them started. Otherwise I'd expect it to happen in the medium-term future.

**Comment by bergwolf** [comment]
@sboeuf I'm still hesitating on this one. Please see my comments on [the agent PR](https://github.com/kata-containers/agent/pull/263#issuecomment-406839542)

File: proxy.go [hunk 4]
```diff
@@ -47,15 +47,39 @@ var sandboxID string
...
 	// Disable keepAlive since we don't know how much time a container can be paused
 	sessionConfig.EnableKeepAlive = false
+	sessionConfig.ConnectionWriteTimeout = time.Second
 	session, err := yamux.Client(servConn, sessionConfig)
 	if err != nil {
 		return nil, err
 	}
 
+	// Start the heartbeat in a separate go routine
+	go heartBeat(session)
```
Comment (jodh-intel) [inline proxy.go]: Since this is a temporary fix, could you add a little more explanation in the code (and ideally a link to an issue so we don't forget about this)?

**Comment by bergwolf** [comment]
LGTM. Thanks for the explanations @sboeuf !
