### PR TITLE
disable yamux keep alive

### LINKED ISSUE #70: yamux: keepalive failed: i/o deadline reached
see https://github.com/kata-containers/agent/issues/231

### PR DESCRIPTION
**Pull request by devimc**
We don't know how much time a container can be paused, hence connection
write timeout should be disabled to don't close the connection while
the container is paused.

fixes kata-containers/agent#231
fixes #70

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

File: proxy.go [hunk 1]
```diff
@@ -43,7 +45,13 @@ var crashOnError = false
 var proxyLog = logrus.New()
 
 func serve(servConn io.ReadWriteCloser, proto, addr string, results chan error) (net.Listener, error) {
-	session, err := yamux.Client(servConn, nil)
+	sessionConfig := yamux.DefaultConfig()
+	sessionConfig.EnableKeepAlive = true
+	// 10 seconds is too early to suspect that a problem with the underlying connection has occurred.
+	// Since we don't know how much time a container can be paused let's set this timeout to 100 years,
+	// probably we won't be there when that occurs ;(
+	sessionConfig.ConnectionWriteTimeout = year * 100
```
Comment (jodh-intel) [inline proxy.go]: Ha! That made my day! :smile:

Comment (sboeuf) [reply proxy.go]: LOL !

@devimc is there any way to disable this timeout ? Something like providing 0 or -1 ?

Comment (devimc) [reply proxy.go]: hahahaha - dahh - good point, let me try  xD

**Comment by devimc** [comment]
changes applied, thanks :)

**Comment by devimc** [comment]
let's wait a little for this PR https://github.com/kata-containers/tests/pull/311

**Comment by devimc** [comment]
https://github.com/kata-containers/tests/pull/311 is green, we can merge it  :)

**Comment by bergwolf** [comment]
What's the benefit of keeping the proxy alive after a sandbox is paused? I think we can just kill the proxy process on pause and start it again when sandbox is resumed.

**Comment by devimc** [comment]
@bergwolf good point, did you file an issue for that ?

**Comment by sboeuf** [comment]
@bergwolf I am wondering if pausing the sandbox is really the thing to do here. Maybe we should not pause the VM and instead pause the container process directly inside the VM.
